name: Lint PHP code style issues

on:
  pull_request:
    paths:
      - '**.php'

jobs:
  lint-php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PHP code style issues
        uses: aglipanci/laravel-pint-action@2.0.0
        with:
          preset: laravel
          verboseMode: true
          testMode: true
